HZN_EXCHANGE_USER_AUTH: ""
HZN_ORG_ID: ""
HZN_FSS_CSSURL: ""
AGENT_NAMESPACE: ""
EDGE_CLUSTER_STORAGE_CLASS: ""
K8S_AUTH_HOST: ""
K8S_AUTH_USERNAME: ""
K8S_AUTH_PASSWORD: ""
K8S_AUTH_TOKEN: ""
OCP_USER: ""
HZN_AGENT_PORT: 8510
HZN_EXCHANGE_URL: ""
HZN_NODE_ID: ""